version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: asia_dtu
      POSTGRES_USER: asia_dtu
      POSTGRES_PASSWORD: huy778631
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U asia_dtu -d asia_dtu"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./backend/config.yaml:/app/config.yaml
    ports:
      - "8000:8000"  # Only expose backend port
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://asia_dtu:huy778631@db/asia_dtu
      - REDIS_URL=redis://redis:6379
    command: python main2.py

volumes:
  postgres_data:
  redis_data: